name: Deploy React App to S3

on:
  push:
    branches:
      - main
    paths:
      - 'status_page_app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd status_page_app
          npm install

      - name: Build React app
        run: |
          cd status_page_app
          npm run build

      - name: Deploy to S3
        uses: aws-actions/s3-sync@v2
        with:
          bucket: ${{ secrets.S3_BUCKET_NAME }}
          region: ${{ secrets.AWS_REGION }}
          source-dir: "status_page_app/dist"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@v2
        with:
          distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          paths: "/*"
          aws-region: ${{ secrets.AWS_REGION }}
